### ISSUE TITLE
The requirements.txt file is missing.

### ISSUE THREAD

**Issue by umernaeem217** [AzureWoods/faceRecognition-yolo-facenet#3]
When building the project with pip and installing the packages it give the compatibility issue of tensor flow with other libraries.

**Comment by rafifazzaki** [comment]
> When building the project with pip and installing the packages it give the compatibility issue of tensor flow with other libraries.


i am using this as my requirements.txt

tensorflow==1.13.1
keras==2.2.5
scipy==1.1.0
scikit-learn
opencv-python==3.4.2.16
h5py==2.10
matplotlib
Pillow
requests
psutil
numpy==1.18

hope it helps
